# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/board?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false"
# spring.datasource.username=root
# spring.datasource.password=root

# mybatis.config = mybatis/mybatis-config.xml
# mybatis.mapper-locations = mybatis/mapper/*.xml

server :
  port : 8080

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/board?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver

mybatis :
  type-aliases-package : com.example.SpringEx.service.mapper.ReportMapper
  mapper-locations : mybatis/mapper/*.xml